print("welcome to Name Decorator! ")
print("Please tell me your name: ")
name=input()
print("Hello, " + name+("!"))
print("your name decortated is, <<<" +name+">>>")
print("your name decortated is, (((" +name+")))")
print("your name decortated is, ---" +name+"---")
print("your name decortated is, :):):)" +name+":):):)")
print("your name decortated is, ###" +name+"###")
print("your name decortated is, +++" +name+"+++")
print("your name decortated is, ~~~" +name+"~~~")
print("your name decortated is, ===" +name+"===")
print("Thank you for playing!")


