print("This is a budget calculator. What is your income?") 
income = input() 
print("your income is", income ) 

print("How much are your rent each month? ")
rent= input() 

print("How much are your utilities each month ")
utilities = input() 

print("What is your monthly grocery price?") 
groceries = input() 
subtotalTwo =input(groceries-income)
print("Your grocery price every year is", groceries) 
print("Your income after groceries very year is", subtotalTwo)
print("how much does does your car cost each year?")
car=input()
subtotalThree =input(car-income)
print("your car cost", car, "each year. ")
print("your income after your car each year is", subtotalThree)
totalSubtotal =input(income-utilities-groceries-car)
print("Your total income evey year after you pay for your essentials is", totalSubtotal)
print("Thank you for using budget calculator!")