print("This is a budget calculator. What is your income?") 
income= input() 
print("your income is", income ) 
print("How much are your utilities each year? ")
utilities= input() 
subtotal= input(utilities-income) 
print("your utilities each year is", utilities "Your income each year after utilities is" , subtotal )
